<a href="https://colab.research.google.com/github/Arun-Varghese2312/Breast-Cancer-Dataset/blob/main/Breast_Cancer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Breast Cancer Dataset

In [8]:
# Import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Import dataset
from sklearn.datasets import load_breast_cancer

# Load dataset
data = load_breast_cancer()

# Convert to dataframe
df = pd.DataFrame(data.data, columns=data.feature_names)

# Add target column
df['target'] = data.target

# Display first 5 rows
df.head()

   mean radius  mean texture  ...  worst fractal dimension  target
0        17.99         10.38  ...                  0.11890       0
1        20.57         17.77  ...                  0.08902       0
2        19.69         21.25  ...                  0.08758       0
3        11.42         20.38  ...                  0.17300       0
4        20.29         14.34  ...                  0.07678       0

[5 rows x 31 columns]

In [9]:
# Missing Values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         569 non-null    float64
 15  compactness error        569 non-null    float64
 16  concavity error          569 non-null    float64
 17  concave points error     569 non-null    float64
 18  symmetry error           569 non-null    float64
 19  fractal dimension error  569 non-null    float64
 20  worst radius             569 non-null    float64
 21  worst texture            569 non-null    float64
 22  worst perimeter          569 non-null    float64
 23  worst area               569 non-null    float64
 24  worst smoothness         569 non-null    float64
 25  worst compactness        569 non-null    float64
 26  worst concavity          569 non-null    float64
 27  worst concave points     569 non-null    float64
 28  worst symmetry           569 non-null    float64
 29  worst fractal dimension  569 non-null    float64
 30  target                   569 non-null    int64
dtypes: float64(30), int64(1)
memory usage: 137.9 KB

In [10]:
df.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
target                     0
dtype: int64

In [12]:
# No missing Values found

In [11]:
# Feature Scaling
# Separate Features and target
X = df.drop('target', axis=1)
y = df['target']

# import train test split
from sklearn.model_selection import train_test_split

# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Import Standard Scaler
from sklearn.preprocessing import StandardScaler

# Create Scaler Object
scaler = StandardScaler()

# Fit and transform training data
X_train_scaled = scaler.fit_transform(X_train)

# Transform test data
X_test_scaled = scaler.transform(X_test)

In [13]:
# Feature scaling performed because features have different ranges

In [14]:
# Classifictaion Algorithm Implementation
# Import accuracy matric
from sklearn.metrics import accuracy_score

In [15]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(random_state=42)
lr.fit(X_train_scaled,y_train)
lr_pred=lr.predict(X_test_scaled)
lr_accuracy=accuracy_score(y_test,lr_pred)
print("LR Accuracy:",lr_accuracy)

LR Accuracy: 0.9736842105263158

In [16]:
# LR predicts probability

In [17]:
# Decision tree classifier
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(random_state=42)
dt.fit(X_train_scaled,y_train)
dt_pred=dt.predict(X_test_scaled)
dt_accuracy=accuracy_score(y_test,dt_pred)
print("DT Accuracy:",dt_accuracy)

DT Accuracy: 0.9473684210526315

In [18]:
# DT splits data into branches based on feature values

In [19]:
# Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(random_state=42)
rf.fit(X_train_scaled,y_train)
rf_pred=rf.predict(X_test_scaled)
rf_accuracy=accuracy_score(y_test,rf_pred)
print("RF Accuracy:",rf_accuracy)

RF Accuracy: 0.9649122807017544

In [20]:
# RF combines multiple decisions to improve accuracy

In [22]:
# Support Vector Machine
from sklearn.svm import SVC
svm=SVC(random_state=42)
svm.fit(X_train_scaled,y_train)
svm_pred=svm.predict(X_test_scaled)
svm_accuracy=accuracy_score(y_test,svm_pred)
print("SVM Accuracy:",svm_accuracy)

SVM Accuracy: 0.9824561403508771

In [23]:
# SVM finds best boundary to separate classes

In [24]:
# k Nearest Neighbours
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(X_train_scaled,y_train)
knn_pred=knn.predict(X_test_scaled)
knn_accuracy=accuracy_score(y_test,knn_pred)
print("KNN Accuracy:",knn_accuracy)

KNN Accuracy: 0.9473684210526315

In [26]:
# KNN classifies based on the majority class of nearest neghbourss

In [32]:
# Model Comparison
# Compare all models
results = pd.DataFrame({
    'Model': ['Logistic Regression', 'Decision Tree', 'Random Forest', 'SVM', 'k-NN'],
    'Accuracy': [
        lr_accuracy,
        dt_accuracy,
        rf_accuracy,
        svm_accuracy,
        knn_accuracy
    ]
})

results.sort_values(by='Accuracy', ascending=False)

                 Model  Accuracy
3                  SVM  0.982456
0  Logistic Regression  0.973684
2        Random Forest  0.964912
1        Decision Tree  0.947368
4                 k-NN  0.947368

In [37]:
# Best and Worst Moidel
best_model = results.loc[results['Accuracy'].idxmax(), 'Model']
worst_model = results.loc[results['Accuracy'].idxmin(), 'Model']
print("Best Model:", best_model)
print("Worst Model:", worst_model)

Best Model: SVM
Worst Model: Decision Tree

In [ ]:
# The best performing is SVM and the worst is Decision Tree